branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: bean-dev
    group_suffix: null
environment-defaults:
  bean-dev:
    branch: null
    repository: null
  tkalb:
    branch: null
    repository: null
global:
  application_name: bean
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
